package org.vizhev.certificate.vu.fortyfive.domain.models

class CertificateContent(
    var id: Long = 0,
    var date: String = "",
    var issueTime: String = "",
    var stationStamp: String = "",
    var locomotiveSeries: String = "",
    var trainNumber: String = "",
    var lastWagonNumber: String = "",
    var isLoaded: Boolean = false,
    var weight: String = "",
    var slopeFactor: String = "",
    var axesTwoAndHalf: String = "",
    var axesThreeAndHalf: String = "",
    var axesFive: String = "",
    var axesSix: String = "",
    var axesSixAndHalf: String = "",
    var axesSeven: String = "",
    var axesSevenAndHalf: String = "",
    var axesEight: String = "",
    var axesEightAndHalf: String = "",
    var axesNine: String = "",
    var axesTen: String = "",
    var axesTwelve: String = "",
    var axesFifteen: String = "",
    var pressingPadsTwoAndHalf: String = "",
    var pressingPadsThreeAndHalf: String = "",
    var pressingPadsFive: String = "",
    var pressingPadsSix: String = "",
    var pressingPadsSixAndHalf: String = "",
    var pressingPadsSeven: String = "",
    var pressingPadsSevenAndHalf: String = "",
    var pressingPadsEight: String = "",
    var pressingPadsEightAndHalf: String = "",
    var pressingPadsNine: String = "",
    var pressingPadsTen: String = "",
    var pressingPadsTwelve: String = "",
    var pressingPadsFifteen: String = "",
    var totalAxes: String = "",
    var pressingPadsRequired: String = "",
    var handBrakesRequired: String = "",
    var handBrakeAxes: String = "",
    var brakeNetworkDensity: String = ""
)